# Generated by Django 3.0.7 on 2021-03-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(choices=[('T', 'Tunis'), ('J', 'Jendouba'), ('N', 'Nabeul'), ('A', 'Ariana'), ('K', 'Kef'), ('B', 'Bizerte')], max_length=128),
        ),
    ]
